version: '4.18.0'
services:
  web:
    image: dba:latest
    depends_on:
      - "redis_image"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9901:80"
    links:
      - "redis_image"

  redis_image:
    image: redis
    container_name: cache
    ports:
      - "6379:6379"